module.exports = {
  projects: [
    '<rootDir>/apps/shell',
    '<rootDir>/apps/api',
    '<rootDir>/libs/api-interfaces',
    '<rootDir>/apps/system-platform',
    '<rootDir>/apps/r-factoring',
    '<rootDir>/libs/system-platform/feature-welcome',
    '<rootDir>/libs/api/share/share-core',
    '<rootDir>/libs/api/share/keycloak-app',
    '<rootDir>/libs/web/share/initialize-service',
    '<rootDir>/libs/system-platform/feature-contract',
    '<rootDir>/libs/system-platform/data-access-contract',
    '<rootDir>/libs/system-platform/contract/domain',
    '<rootDir>/libs/system-platform/contract/feature-list',
    '<rootDir>/libs/system-platform/contract/feature-detail',
    '<rootDir>/apps/user',
    '<rootDir>/libs/system/dept',
    '<rootDir>/libs/system/user/domain',
    '<rootDir>/libs/system/user/feature-user',
    '<rootDir>/libs/system/dept/domain',
    '<rootDir>/libs/system/dept/feature-search',
  ],
};
